[package]
name = "e310x"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
riscvimac = { path = "../../arch/riscvimac" }
kernel = { path = "../../kernel" }

